Repository MichaelLELU/OriginsDigital-DigiCode-P3, pull requests merged in 2024-08, with the labels that each got.

#3 Validations and security, console cleanup + more features
  client/index.html
  client/src/components/HeroSlider/HeroSlider.jsx
  client/src/components/categorieslist/CategoriesList.jsx
  client/src/components/filter/Filter.jsx
  client/src/components/footer/Footer.jsx
  client/src/components/navbar/NavBar.jsx
  client/src/components/searchbar/SearchBar.jsx
  client/src/components/videocard/VideoCard.jsx
  client/src/main.jsx
  client/src/pages/adminpage/AdminPage.jsx
  client/src/pages/categoriespage/CategoriesPage.jsx
  client/src/pages/categorypage/CategoryPage.jsx
  client/src/pages/errorpage/Error404Page.jsx
  client/src/pages/homepage/HomePage.jsx
  client/src/pages/loginpage/LoginPage.jsx
  client/src/pages/resultpage/ResultPage.jsx
  client/src/pages/videopage/VideoPage.jsx
  package-lock.json
  server/app/controllers/authController.js
  server/app/controllers/categoryActions.js
  server/app/controllers/videoActions.js
  server/app/routers/api/categories/router.js
  server/app/routers/api/videos/misc/router.js
  server/app/routers/api/videos/router.js
  server/app/services/validation/authValidation.js
  server/app/services/validation/userValidation.js
  server/database/models/CategoryRepository.js
  server/database/models/VideoRepository.js
  server/package.json
Labels: enhancement

#10 feat: security wall into api route for admin
  client/src/components/categoryforms/CategoryAdd.jsx
  client/src/components/categoryforms/CategoryDelete.jsx
  client/src/components/categoryforms/CategoryUpdate.jsx
  client/src/components/userforms/NameUpdate.jsx
  client/src/components/videoforms/VideoAdd.jsx
  client/src/components/videoforms/VideoDelete.jsx
  client/src/components/videoforms/VideoUpdate.jsx
  client/src/pages/signupPage/SignupPage.jsx
  server/app/controllers/userActions.js
  server/app/routers/api/categories/router.js
  server/app/routers/api/users/router.js
  server/app/routers/api/videos/router.js
  server/app/services/adminWall.js
  server/app/services/userWall.js
  server/database/models/UserRepository.js
Labels: enhancement

#5 Adding "favorites" system
  README.md
  client/package.json
  client/src/App.css
  client/src/App.jsx
  client/src/assets/.gitkeep
  client/src/assets/favicon.ico
  client/src/components/.gitkeep
  client/src/components/HeroSlider/HeroSlider.jsx
  client/src/components/categorieslist/CategoriesList.jsx
  client/src/components/filter/Filter.css
  client/src/components/footer/Footer.css
  client/src/components/footer/Footer.jsx
  client/src/components/navbar/NavBar.css
  client/src/components/navbar/NavBar.jsx
  client/src/components/searchbar/SearchBar.css
  client/src/components/searchbar/SearchBar.jsx
  client/src/components/videocard/VideoCard.css
  client/src/components/videocard/VideoCard.jsx
  client/src/main.jsx
  client/src/pages/.gitkeep
  client/src/pages/adminpage/AdminPage.css
  client/src/pages/adminpage/AdminPage.jsx
  client/src/pages/categorypage/CategoryPage.css
  client/src/pages/homepage/HomePage.css
  client/src/pages/loginpage/LoginPage.css
  client/src/pages/resultpage/ResultPage.css
  client/src/pages/signupPage/SignupPage.css
  client/src/pages/userpage/UserPage.css
  client/src/pages/userpage/UserPage.jsx
  client/src/pages/videopage/VideoPage.css
  client/src/pages/videopage/VideoPage.jsx
  client/src/services/.gitkeep
  client/src/utils/addFavorites.js
  client/src/utils/addHerosliderVideo.js
  client/src/utils/auth.js
  client/src/utils/removeFavorites.js
  client/src/utils/removeHerosliderVideo.js
  client/src/variables.css
  package-lock.json
  server/app/controllers/authController.js
  server/app/controllers/favoriteController.js
  server/app/controllers/herosliderActions.js
  server/app/controllers/videoActions.js
  server/app/routers/api/favorite/router.js
  server/app/routers/api/heroslider/router.js
  server/app/routers/api/router.js
  server/app/routers/api/videos/misc/router.js
  server/app/services/.gitkeep
  server/database/fixtures/VideoSeeder.js
  server/database/models/FavoriteRepository.js
  server/database/models/HerosliderRepository.js
  server/database/models/VideoRepository.js
  server/database/tables.js
Labels: enhancement

#12 Exo2 font
  client/src/App.css
  client/src/assets/fonts/Exo-VariableFont_wght.ttf
  client/src/assets/fonts/Exo2-VariableFont_wght.ttf
  client/src/components/searchbar/SearchBar.jsx
Labels: enhancement

#13 little navbar "fix"
  client/src/components/navbar/NavBar.jsx
Labels: minor change

#17 feat: added dynamic titles
  client/src/pages/adminpage/AdminPage.jsx
  client/src/pages/categoriespage/CategoriesPage.jsx
  client/src/pages/categorypage/CategoryPage.jsx
  client/src/pages/errorpage/Error404Page.jsx
  client/src/pages/homepage/HomePage.jsx
  client/src/pages/loginpage/LoginPage.jsx
  client/src/pages/resultpage/ResultPage.jsx
  client/src/pages/rgpdpage/rgpdPage.jsx
  client/src/pages/signupPage/SignupPage.jsx
  client/src/pages/userpage/UserPage.jsx
  client/src/pages/videopage/VideoPage.jsx
  client/src/utils/setPageTitle.js
Labels: enhancement, minor change

#14 fix: add heroslider on adminpage
  client/src/components/HeroSlider/HeroSlider.css
  client/src/components/HeroSlider/HeroSlider.jsx
  client/src/pages/adminpage/AdminPage.jsx
  client/src/pages/signupPage/SignupPage.css
Labels: minor change
